### ISSUE TITLE
Workspace ID doesn't exist

### ISSUE THREAD

**Issue by oopsii** [paveldournov/RRSWarmer#1]
![antis](https://cloud.githubusercontent.com/assets/6470784/9951466/34ad8654-5df9-11e5-8d94-4f8ce59974c4.PNG)

I have tried with several different experiments in several different workspaces, but to no availl. Am always getting the workspace ID error. Any know issue like this?

**Comment by paveldournov** [comment]
This can happen when you pass a wrong workspaceID to the tool. Please post the issue to AzureML forum so that someone from the AzureML team can engage and investigate. https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=MachineLearning

**Comment by paveldournov** [comment]
The problem was most likely caused by the web service being in a non US region. The warmer tool is now updated to handle web services in other regions. It should fix the problem with workspace not found. Please try it out.
